name: push gescom to Docker Hub

on:
  push:
    branches: [v-abd]
  pull_request:
    branches: [v-abd]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.21.3' 
        id: install

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gescom
    
      - name: Update kube config
        run: aws eks update-kubeconfig --name ids-prod --region eu-west-3

      - name: Deploy gescom to Amazon EKS
        run:  |
              kubectl delete deployments.apps --namespace gescom gescom
              kubectl apply -f deploy/deploy.yaml